accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')
]

cartapp/urls.py
from django.urls import path

from cartapp import views

urlpatterns=[
    path('addtocart/<int:id>',views.addtocart,name='addtocart'),
    path('cartlist',views.cartlist,name='cartlist'),
   # path('delete',views.delete,name='delete')

]

demo1/urls.py
from django.urls import path

from demo1 import views

urlpatterns = [
    path('',views.home,name='home'),
    path('add',views.sum,name='sum')
]

demoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

import accounts

urlpatterns = [
    path('',include('musicalapp.urls')),
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include(('cartapp.urls','cartapp'),namespace='cartapp'))
    ]

urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

musicalapp/urls.py
from django.urls import path
from musicalapp import views
urlpatterns = [
    path('',views.index,name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

cartapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from musicalapp.models import Instrument


class Cart(models.Model):
    insrument=models.ForeignKey(Instrument,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

class Order(models.Model):
    totaBill=models.IntegerField()
    status=models.CharField(max_length=30,default="processing")
    order_date=models.DateField(auto_now=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

demo1/models.py
from django.db import models

# Create your models here.

musicalapp/models.py
from django.db import models

# Create your models here.
class Instrument(models.Model):
    # id:int
    # name:str
    # img:str
    # price:float
    # desc:str

    name=models.CharField(max_length=100)
    desc=models.TextField()
    price=models.FloatField()
    img=models.ImageField(upload_to='pics')

accounts/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    if request.method == 'POST':
        firstName=request.POST['fname']
        lastName=request.POST['lname']
        userName=request.POST['uname']
        email=request.POST['email']
        pass1=request.POST['pass1']
        pass2=request.POST['pass2']
        if pass1==pass2:
            if User.objects.filter(username=userName).exists():
                messages.info(request,'UserName already exists')
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,'Email ID already exists')
                return redirect('register')
            else:

                u=User.objects.create_user(username=userName,first_name=firstName,last_name=lastName,email=email,password=pass1)
                u.save()
                messages.info(request,"You have successfully registerd!")
                return render(request,'index.html')
        else:
            messages.info(request,'Password not matching')
            return redirect('register')
    else:
        return render(request,'register.html')




def login(request):
        if request.method=='POST':
            uname=request.POST['username']
            password=request.POST['password']
            u=auth.authenticate(username=uname,password=password)
            if u is not None:
                request.session['uid']=u.id
                auth.login(request,u)
                return redirect("/")
            else:
                messages.info(request,"Login fail! Invalid credentials")
                return redirect("login")
        else:
            return render(request,'login.html')

def logout(request):
    auth.logout(request)
    messages.info(request,"You have logged out! Visit Again")
    return redirect("/")

cartapp/views.py
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import render, redirect

# Create your views here.
from cartapp.models import Cart, Order
from musicalapp.models import Instrument


def addtocart(request, id):
   c=Cart()
   instrumentid=Instrument.objects.get(id=id)
   uid=request.session.get('uid')
   userid=User.objects.get(id=uid)
   c.insrument=instrumentid
   c.user=userid
   c.save()
   messages.info(request,"Cart Added successfully")
   return redirect("/")


def cartlist(request):
   uid=request.session.get('uid')
   cr=Cart.objects.filter(user=uid)
   if request.method=="POST":
     totalbill=0
     qty=int(request.POST['qty'])
     for i in cr:
        totalbill=totalbill+i.insrument.price *qty
     o=Order()
     o.totaBill=totalbill
     o.user=User.objects.get(id=uid)
     o.status='completed'
     o.save()
     for i in cr:
        i.delete()
     return render(request,'index.html',{'totalbill':totalbill})

   else:

     d={'cr':cr}
     return render(request,"cartlist.html",d)

demo1/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
   # return HttpResponse("HELLO DJANGO WORLD")
   return render(request,'sample.html',{'name':'mahendra'})


def sum(request):
   a=int(request.POST['no1'])
   b=int(request.POST['no2'])
   ans=a+b
   return render(request,'result.html',{'result':ans})   

musicalapp/views.py
from django.shortcuts import render

# Create your views here.
from musicalapp.models import Instrument


def index(request):
    # it=Instrument()
    # it.name="Guitar"
    # it.desc="Its a string instrument"
    # it.price=10000
    # it.img="guitar.jpg"
    details=Instrument.objects.all()
    return render(request,"index.html",{'it':details})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body bgcolor="lightblue">
{% block content %}
{% endblock %}
</body>
</html>

templates/cartlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="cartlist" method="post">
    {% csrf_token %}
    <table border="2" cellspacing="20" cellpadding="20">
        <tr>
            <th>CartId</th>
            <th>InstrumentName</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Action</th>
        </tr>
        {% for i in cr %}
        <tr>
            <td>{{ i.id }}</td>
            <td>{{ i.insrument.name}}</td>
            <td>{{ i.insrument.price}}</td>
            <td><input type="number"name="qty" value="1"></td>
<!--            <td><a href="">Delete</a></td>-->
        </tr>
        {% endfor %}
        <tr>
            <td colspan="4"><input type="submit" value="Place Order"></td>
        </tr>
    </table>
</form>
</body>
</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%load static %}

<div class="footer">
				<div class="wrap">
				<div class="section group">
				<div class="col_1_of_4 span_1_of_4">
					<h3>INFORMATION</h3>
					<ul>
						<li><a href="#">About us</a></li>
						<li><a href="#">Sitemap</a></li>
						<li><a href="#">Contact</a></li>
						<li><a href="#">Terms and conditions</a></li>
						<li><a href="#">Legal Notice</a></li>
					</ul>
				</div>
				<div class="col_1_of_4 span_1_of_4">
					<h3>OUR OFFERS</h3>
					<ul>
						<li><a href="#">New products</a></li>
						<li><a href="#">top sellers</a></li>
						<li><a href="#">Specials</a></li>
						<li><a href="#">Products</a></li>
						<li><a href="#">Comments</a></li>
					</ul>
				</div>
				<div class="col_1_of_4 span_1_of_4">
					<h3>YOUR ACCOUNT</h3>
					<ul>
						<li><a href="#">Your Account</a></li>
						<li><a href="#">Personal info</a></li>
						<li><a href="#">Prices</a></li>
						<li><a href="#">Address</a></li>
						<li><a href="#">Locations</a></li>
					</ul>
				</div>
				<div class="col_1_of_4 span_1_of_4 footer-lastgrid">
					<h3>Get in touch</h3>
					<ul>
						<li><a href="#"><img src="{% static 'images/facebook.png' %}" title="facebook" /></a></li>
						<li><a href="#"><img src="{% static 'images/twitter.png' %}" title="Twiiter" /></a></li>
						<li><a href="#"><img src="{% static 'images/rss.png' %}" title="Rss" /></a></li>
						<li><a href="#"><img src="{% static 'images/gpluse.png' %}" title="Google+" /></a></li>
					</ul>
					<p>Design by <a href="#">mahendra</a></p>
				</div>
			</div>
			</div>
</div>
</body>
</html>

templates/header.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"  media="all" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'css/responsiveslides.css' %}">
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>
<body>


	<!---start-header--->
			<div class="header">
			<!---start-top-header--->
			<div class="top-header">

				<div class="clear"> </div>
			</div>
			<div class="clear"> </div>
			<div class="sub-header">
				<div class="logo">
					<a href="/"><img src="{% static 'images/logo.png' %}" title="logo" /></a>
				</div>
				<div class="sub-header-center">
					<form>
						<input type="text"><input type="submit"  value="search" />
					</form>
				</div>
				<div class="clear"> </div>
			</div>
			<div class="clear"> </div>
			<div class="top-nav">
				<ul>
					<li class="active1"><a href="/">Home</a></li>

                    {% if user.is_authenticated %}

                    <li><a href="logout">Logout</a></li>
                    <li><a href="{% url 'cartapp:cartlist' %}">show Cart</a></li>
					<li>Hello {{user.first_name}} welcome to this website!</li>
                    {% else %}
                    <li><a href="register">Register</a></li>
					<li><a href="login">Login</a></li>
                    <li><a href="admin/">AdminLogin</a></li>
                    {% endif %}
					<div class="clear"> </div>
				</ul>
			</div>
			<!---end-top-header--->
			<!---End-header--->
			</div>
</body>
</html>

templates/index.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{%load static %}
{% static 'images' as baseurl %}
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>OnlinemusicalStore</title>
		<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"  media="all" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'css/responsiveslides.css' %}">
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
		<script src="{% static 'js/responsiveslides.min.js' %}"></script>
		  <script>
		     "$(window).load(function() {"
			    $(function () {
			
			    
			      $("#slider1").responsiveSlides({
			        maxwidth: 1600,
			        speed: 600
			      });
			});
		  </script>
	</head>
	<body>

		<!---start-wrap--->
		<div class="wrap">
          {% include 'header.html' %}
			{% if totalbill > 0 %}
			<div>
				<h2 style="color:red">Order Placed successfully! Your Total Bill is:-{{totalbill}}</h2>
			</div>
			{% endif %}
				<div>
                    {% for m in messages %}
					<h2 style="color:red">{{m}}</h2>
					{% endfor %}
				</div>
			
				<!--start-image-slider---->
					<div class="image-slider">
						<!-- Slideshow 1 -->
					    <ul class="rslides" id="slider1">
					      <li><img src="{% static 'images/slider1.jpg' %}" alt=""></li>
					      <li><img src="{% static 'images/slider6.jpg' %}" alt=""></li>
					      <li><img src="{% static 'images/slider2.jpg' %}" alt=""></li>
					    </ul>
						 <!-- Slideshow 2 -->
					</div>
					<!--End-image-slider---->
				<div class="content">
					<div class="products-box">
					<div class="products">
						<h5><span>FEATURED</span> PRODUCTS</h5>
						<div class="section group">
							{% for i in it %}
							  <div class="grid_1_of_5 images_1_of_5">
								 <img src="{{i.img.url}}" height="210", width="210">
								 <h3>{{i.name}}</h3>
								 <p>{{i.desc}}</p>
								 <h4>{{i.price}}</h4>
								{% if user.is_authenticated %}
							     <div class="button"><span><a href="{% url 'cartapp:addtocart' i.id %}">AddToCart</a></span></div>
								{% endif %}
						      </div>
							{% endfor %}

						<div class="clear"> </div>
					</div>
						<div class="clear"> </div>
						</div>
					</div>
				</div>
			</div>
		</div>
			<div class="clear"> </div>
        {% include 'footer.html' %}
		</div>
		<!---End-wrap--->
	</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
      <style>
        th{color: white}
    </style>
</head>
<body>
 {% include 'header.html' %}
  <br> <br> <br> <br><br>
<div>
    {% for m in messages %}
    <h2 style="color:red">{{m}}</h2>
    {% endfor %}
</div>
<form action="login" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <th> UserName</th>
            <td><input type="text" name="username"</td>
        </tr>
        <tr>
            <th> Password</th>
            <td><input type="password" name="password"</td>
        </tr>
        <tr>
            <td align="center" colspan="2"> <input type="submit" value="Login">
            <input type="reset" value="clear"</td>
        </tr>
    </table>
</form>
 <br> <br> <br> <br><br>
{% include 'footer.html' %}
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register here</title>
    <style>
        th{color: white}
    </style>
</head>
<body>
 {% include 'header.html' %}
  <br> <br> <br> <br><br>
<div>
    {% for m in messages %}
    <h2 style="color:red">{{m}}</h2>
    {% endfor %}
</div>
<form action="register" method="post">
    {% csrf_token %}
    <table align="center" border="2">
        <tr>
            <th>FirstName</th>
            <td><input type="text" name="fname"></td>
        </tr>

          <tr>
            <th>LastName</th>
            <td><input type="text" name="lname"></td>
        </tr>

          <tr>
            <th>UserName</th>
            <td><input type="text" name="uname"></td>
        </tr>

          <tr>
            <th>EmailId</th>
            <td><input type="email" name="email"></td>
        </tr>

          <tr>
            <th>Password</th>
            <td><input type="password" name="pass1"></td>
        </tr>

          <tr>
            <th>Confirm Password</th>
            <td><input type="password" name="pass2"></td>
        </tr>
         <td align="center" colspan="2"><input type="submit" value="Register">
          <input type="reset" value="Cancel"></td>
    </table>
</form>
  <br> <br> <br> <br><br>
{% include 'footer.html' %}
</body>
</html>

templates/result.html
<html>
    <heand>
        <title>
        </title>
    </heand>
    <body>
        <h2>addition of no is:{{result}}</h2>
    </body>
</html>

templates/sample.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
<body>
{% extends 'base.html' %}
{% block content %}
<h2>welcome {{name}}</h2>
<form action="add" method="post">
    {% csrf_token %}
    <label> Enter 1st number</label>
    <input type="text" name="no1"><br>
    <label> Enter 2nd number</label>
    <input type="text" name="no2"><br>
    <input type="submit" value="Add">
</form>
{% endblock %}
</body>
</html>